name: task-a cd

on: [push]

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: pip install -r task_a/requirements.txt

      - name: Run pytest with HTML report
        run: pytest task_a/task_a.py --html=report.html --self-contained-html

      - name: Upload pytest report
        uses: actions/upload-artifact@v4
        with:
          name: Report-ubuntu-3.11
          path: report.html
